name: Bot Run

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  GitHubMail: "xenon@xenon.com"
  GitHubName: "xenon" 
  Branch: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
          
      - name: Clone the bot files
        run: |
          git clone https://github.com/Tanmay2k3/Evelin.NET -b ${Branch} source

      - name: Installing Dependencies
        run: |
          cd source || exit 1
          dotnet add package Discord.NET
          dotnet add package Discord.Addons.Hosting
          dotnet add package Microsoft.Extensions.Configuration
          dotnet add package Microsoft.Extensions.Hosting
          dotnet add package Microsoft.Extensions.DependencyInjection

      - name: Running DotNET
        timeout-minutes: 340
        continue-on-error: true
        run: |
          dotnet run Program.cs

      - name: Loop Workflow
        continue-on-error: true
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
